
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kmora
 */
public class BurgersRUsGUI extends javax.swing.JFrame {
    
    // class level reference and attributes
    private double orderTotal;

    /**
     * Creates new form BurgersRUsGUI
     */
    public BurgersRUsGUI() {
        initComponents();
        
        // set to center of screen
        this.setLocationRelativeTo(null);
        orderTotal = 0.0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        btgBurgers = new javax.swing.ButtonGroup();
        rdoSingle = new javax.swing.JRadioButton();
        rdoDouble = new javax.swing.JRadioButton();
        chkCheese = new javax.swing.JCheckBox();
        chkBacon = new javax.swing.JCheckBox();
        chkMeal = new javax.swing.JCheckBox();
        lblItemPrice = new javax.swing.JLabel();
        txtItemPrice = new javax.swing.JTextField();
        lblReceipt = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblOrderTotal = new javax.swing.JLabel();
        txtOrderTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaReceipt = new javax.swing.JTextArea();
        jmbMainMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniExit = new javax.swing.JMenuItem();
        mnuOrder = new javax.swing.JMenu();
        mniAddToOrder = new javax.swing.JMenuItem();
        mniClearForNextItem = new javax.swing.JMenuItem();
        mniNewOrder = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Burger Barn");

        btgBurgers.add(rdoSingle);
        rdoSingle.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdoSingle.setText("Single Burger");
        rdoSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoSingleActionPerformed(evt);
            }
        });

        btgBurgers.add(rdoDouble);
        rdoDouble.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        rdoDouble.setText("Double Burger");
        rdoDouble.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoDoubleActionPerformed(evt);
            }
        });

        chkCheese.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkCheese.setText("Add Cheese");
        chkCheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCheeseActionPerformed(evt);
            }
        });

        chkBacon.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkBacon.setText("Add Bacon");
        chkBacon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBaconActionPerformed(evt);
            }
        });

        chkMeal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        chkMeal.setText("Make It a Meal");
        chkMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMealActionPerformed(evt);
            }
        });

        lblItemPrice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblItemPrice.setText("Item Price:");

        txtItemPrice.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtItemPrice.setText("0");

        lblReceipt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReceipt.setText("Your Order");

        lblQuantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuantity.setText("Quantity:");

        txtQuantity.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblOrderTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblOrderTotal.setText("Order Total:");

        txtOrderTotal.setEditable(false);
        txtOrderTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        txaReceipt.setColumns(20);
        txaReceipt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txaReceipt.setRows(5);
        jScrollPane1.setViewportView(txaReceipt);

        mnuFile.setText("File");

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        jmbMainMenu.add(mnuFile);

        mnuOrder.setText("Order");

        mniAddToOrder.setText("Add to Order");
        mniAddToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAddToOrderActionPerformed(evt);
            }
        });
        mnuOrder.add(mniAddToOrder);

        mniClearForNextItem.setText("Clear For Next Item");
        mniClearForNextItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClearForNextItemActionPerformed(evt);
            }
        });
        mnuOrder.add(mniClearForNextItem);

        mniNewOrder.setText("New Order");
        mniNewOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewOrderActionPerformed(evt);
            }
        });
        mnuOrder.add(mniNewOrder);

        jmbMainMenu.add(mnuOrder);

        setJMenuBar(jmbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoSingle)
                        .addGap(196, 196, 196)
                        .addComponent(lblReceipt))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblItemPrice)
                            .addGap(18, 18, 18)
                            .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(73, 73, 73)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblQuantity)
                                    .addGap(47, 47, 47)
                                    .addComponent(txtQuantity))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblOrderTotal)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(chkBacon)
                                .addComponent(chkMeal)
                                .addComponent(chkCheese)
                                .addComponent(rdoDouble))
                            .addGap(72, 72, 72)
                            .addComponent(jScrollPane1))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSingle)
                    .addComponent(lblReceipt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdoDouble)
                        .addGap(18, 18, 18)
                        .addComponent(chkCheese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkBacon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkMeal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblQuantity)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblOrderTotal)
                            .addComponent(txtOrderTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniExitActionPerformed
        // close the application
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void rdoSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoSingleActionPerformed
        // update item price for the burger
        updateItemPrice();
    }//GEN-LAST:event_rdoSingleActionPerformed

    private void rdoDoubleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoDoubleActionPerformed
        // update item price for the burger
        updateItemPrice();
    }//GEN-LAST:event_rdoDoubleActionPerformed

    private void chkCheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCheeseActionPerformed
        // update item price for the burger
        updateItemPrice();
    }//GEN-LAST:event_chkCheeseActionPerformed

    private void chkBaconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBaconActionPerformed
        // update item price for the burger
        updateItemPrice();
    }//GEN-LAST:event_chkBaconActionPerformed

    private void chkMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMealActionPerformed
        // update item price for the burger
        updateItemPrice();
    }//GEN-LAST:event_chkMealActionPerformed

    private void mniAddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAddToOrderActionPerformed
        // build the output line
        String outputLine = txtQuantity.getText();
        if( rdoSingle.isSelected() )
            outputLine += " single";
        else 
            outputLine += " double";
        
        if( chkCheese.isSelected() )
            outputLine += ", cheese";
        
        if( chkBacon.isSelected() )
            outputLine += ", bacon";
        
        if( chkMeal.isSelected() )
            outputLine += ", meal";
        
        outputLine += " at ";
        outputLine += txtItemPrice.getText();
        outputLine += " each\n";
        
        txaReceipt.append(outputLine);
        
        // update the orderTotal
        int quantity = Integer.parseInt( txtQuantity.getText() );
        double itemPrice = Double.parseDouble( txtItemPrice.getText() );
        double linePrice = quantity * itemPrice;
        
        orderTotal += linePrice;
        DecimalFormat fmt = new DecimalFormat("#, ##0.00");
        txtOrderTotal.setText(fmt.format(orderTotal));
        
        
        
        // update orderTotal
    }//GEN-LAST:event_mniAddToOrderActionPerformed

    private void mniClearForNextItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniClearForNextItemActionPerformed
        clearForNextItem();
        
    }//GEN-LAST:event_mniClearForNextItemActionPerformed

    private void mniNewOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniNewOrderActionPerformed
        clearForNextItem();
        txaReceipt.setText("");
        txtOrderTotal.setText("");
        orderTotal = 0.0;
        
    }//GEN-LAST:event_mniNewOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgersRUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgersRUsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgBurgers;
    private javax.swing.JCheckBox chkBacon;
    private javax.swing.JCheckBox chkCheese;
    private javax.swing.JCheckBox chkMeal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuBar jmbMainMenu;
    private javax.swing.JLabel lblItemPrice;
    private javax.swing.JLabel lblOrderTotal;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReceipt;
    private javax.swing.JMenuItem mniAddToOrder;
    private javax.swing.JMenuItem mniClearForNextItem;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniNewOrder;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuOrder;
    private javax.swing.JRadioButton rdoDouble;
    private javax.swing.JRadioButton rdoSingle;
    private javax.swing.JTextArea txaReceipt;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtOrderTotal;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void updateItemPrice() {
        double itemPrice = 0;
        
        // get the burger size
        if( rdoSingle.isSelected())
            itemPrice = 3.50;
        else if ( rdoDouble.isSelected())
            itemPrice = 4.75;
        else
        {
            JOptionPane.showMessageDialog(this, "Burger tpe must be selected.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // add charges for the options
        if( chkCheese.isSelected())
            itemPrice += 0.50;  // itemPrice = itemPrice + 0.50;
        
        if( chkBacon.isSelected())
            itemPrice += 1.25;
        
        if( chkMeal.isSelected())
            itemPrice += 4.00;
        
        // show the item price
        DecimalFormat fmt = new DecimalFormat("#, ##0.00");
        txtItemPrice.setText(fmt.format(itemPrice) );
    }

    private void clearForNextItem() {
        // clear for next item
        btgBurgers.clearSelection();
        chkCheese.setSelected(false);
        chkBacon.setSelected(false);
        chkMeal.setSelected(false);
        txtItemPrice.setText("0");
        txtQuantity.setText("1");
    }
}
