
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;


/**************************************************** 
Program Name: GradeManagement.java 
Programmer's Name: Kamil Moralewski 
Program Description: GUI for GradeManagement Program
***********************************************************/

public class GradeManagement extends javax.swing.JFrame {

    /**
     * Creates new form GradeManagement
     */
    public GradeManagement() {
        initComponents();
        
        // center the form
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblTest1 = new javax.swing.JLabel();
        txtTest1 = new javax.swing.JTextField();
        lblTest2 = new javax.swing.JLabel();
        txtTest2 = new javax.swing.JTextField();
        lblTest3 = new javax.swing.JLabel();
        txtTest3 = new javax.swing.JTextField();
        btnAddStudent = new javax.swing.JButton();
        btnDisplayAll = new javax.swing.JButton();
        scrStudents = new javax.swing.JScrollPane();
        txaStudents = new javax.swing.JTextArea();
        scrStudentTable = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grade Management System");

        lblName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblName.setText("Name:");

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblTest1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTest1.setText("Test 1:");

        txtTest1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblTest2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTest2.setText("Test 2:");

        txtTest2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        lblTest3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTest3.setText("Test 3:");

        txtTest3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnAddStudent.setText("Add Student");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });

        btnDisplayAll.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnDisplayAll.setText("Display All");
        btnDisplayAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayAllActionPerformed(evt);
            }
        });

        txaStudents.setColumns(20);
        txaStudents.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txaStudents.setRows(5);
        scrStudents.setViewportView(txaStudents);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrStudentTable.setViewportView(tblStudents);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grades.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddStudent)
                        .addGap(18, 18, 18)
                        .addComponent(btnDisplayAll))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTest1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTest2)
                                .addGap(18, 18, 18)
                                .addComponent(txtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTest3)
                                .addGap(18, 18, 18)
                                .addComponent(txtTest3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrStudents)
                    .addComponent(scrStudentTable))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest1)
                            .addComponent(txtTest1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest2)
                            .addComponent(txtTest2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTest3)
                            .addComponent(txtTest3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddStudent)
                    .addComponent(btnDisplayAll))
                .addGap(18, 18, 18)
                .addComponent(scrStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrStudentTable, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        // get student information
        String stuName = txtName.getText();
        double test1 = Double.parseDouble( txtTest1.getText() );
        double test2 = Double.parseDouble( txtTest2.getText() );
        double test3 = Double.parseDouble( txtTest3.getText() );
        
        // create tudent object
        Student stu = new Student(0, stuName, test1, test2, test3);
        
        // add the student to the datbase using the StudentDB object
        StudentDB db = new StudentDB();
        db.add(stu);
        JOptionPane.showMessageDialog(this, "Record was written to the database.");
        // clear the form
        txtName.setText("");
        txtTest1.setText("");
        txtTest2.setText("");
        txtTest3.setText("");
        txtName.requestFocus(); // put cursor back on the Name field

    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void btnDisplayAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayAllActionPerformed
        // show output to text area
        txaStudents.setText("Name" + "\t" + "Test1" + "\t" + "Test 2" + "\t" + "Test3" + "\t" + "Average" + "\t" + "Grade" + "\n");
        
        // read the student records
        StudentDB db = new StudentDB();
        ArrayList<Student> data = db.getAll();
        DecimalFormat fmt = new DecimalFormat("0.0");
        for( int i = 0; i < data.size(); i++ ) {
            Student stu = data.get(i);
            txaStudents.append( stu.getName() + "\t" + stu.getTest1() + "\t" + stu.getTest2() + "\t"
                    + stu.getTest3() + "\t" + fmt.format(stu.calculateAverage()) + "\t" + stu.calculateLetterGrade() + "\n");
        }
        
        //=======================================
        // display record on a JTable
        //=======================================
        
        // show the headings
        DefaultTableModel tblModel = new DefaultTableModel();
        tblStudents.setModel(tblModel);
        
        String[] colTitles = { "Name", "Test1", "Test2", "Test3", "Average", "Grade" };
        tblModel.setColumnIdentifiers(colTitles);
        
        StudentDB db2 = new StudentDB();
        DecimalFormat fmt2 = new DecimalFormat("0.0");
        ArrayList<Student> records = db2.getAll();
        
        for( int i = 0; i < data.size(); i++ ) {
            Student stu = data.get(i);
            
            Object[] row = { stu.getName(), stu.getTest1(), stu.getTest3(),
                fmt2.format(stu.calculateAverage()), stu.calculateLetterGrade() };
            
            tblModel.addRow(row);
        }
        
        
    }//GEN-LAST:event_btnDisplayAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnDisplayAll;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTest1;
    private javax.swing.JLabel lblTest2;
    private javax.swing.JLabel lblTest3;
    private javax.swing.JScrollPane scrStudentTable;
    private javax.swing.JScrollPane scrStudents;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTextArea txaStudents;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtTest1;
    private javax.swing.JTextField txtTest2;
    private javax.swing.JTextField txtTest3;
    // End of variables declaration//GEN-END:variables
}
